### ISSUE TITLE
deployHeroku no-ops in CircleCI environment

### ISSUE THREAD

**Issue by tel** [heroku/heroku-sbt-plugin#31]
Pretty much what the title claims. When trying to use CircleCI to deploy to Heroku with the deployHeroku task I see a complete no-op:

```
sbt server/stage server/deployHeroku
[info] Loading project definition from /home/ubuntu/qubit/project
[INFO] [05/19/2016 03:29:10.144] [Workbench-System-akka.actor.default-dispatcher-3] [akka://Workbench-System/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:12345
[INFO] [05/19/2016 03:29:10.147] [Workbench-System-akka.actor.default-dispatcher-4] [akka://Workbench-System/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://Workbench-System/user/IO-HTTP/listener-0#-423801860] to Actor[akka://Workbench-System/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[info] Set current project to qubit (in build file:/home/ubuntu/qubit/)
[info] Packaging /home/ubuntu/qubit/server/target/scala-2.11/server_2.11-1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Wrote /home/ubuntu/qubit/server/target/scala-2.11/server_2.11-1.0-SNAPSHOT.pom
[info] Main Scala API documentation to /home/ubuntu/qubit/server/target/scala-2.11/api...
[info] Packaging /home/ubuntu/qubit/server/target/scala-2.11/server_2.11-1.0-SNAPSHOT.jar ...
[info] Done packaging.
model contains 21 documentable templates
[info] Main Scala API documentation successful.
[info] Packaging /home/ubuntu/qubit/server/target/scala-2.11/server_2.11-1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] Packaging /home/ubuntu/qubit/shared/.jvm/target/scala-2.11/sharedjvm_2.11-1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Packaging /home/ubuntu/qubit/shared/.jvm/target/scala-2.11/sharedjvm_2.11-1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] Packaging /home/ubuntu/qubit/shared/.jvm/target/scala-2.11/sharedjvm_2.11-1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Wrote /home/ubuntu/qubit/shared/.jvm/target/scala-2.11/sharedjvm_2.11-1.0-SNAPSHOT.pom
[success] Total time: 13 s, completed May 19, 2016 3:29:23 AM
[success] Total time: 0 s, completed May 19, 2016 3:29:23 AM
```

**Comment by jkutner** [comment]
does the same command work locally?

**Comment by tel** [comment]
It does, yes. I'm also double checking that my HEROKU_API_KEY is correctly configured in the build environment.

**Comment by jkutner** [comment]
A bad api key should cause a specific error message. The other thing would be the appName (do you have that set in the `build.sbt`?). But I would expect appName to error out too.

**Comment by jkutner** [comment]
Can you try enabling debug logging on Circle CI? I think you can do this by adding `logLevel := Level.Debug` to your `build.sbt`.

**Comment by tel** [comment]
I tried the log level but and the response was the same: no logs :/

App Name is being set in my build.sbt

**Comment by joseraya** [comment]
I had a similar problem with a module and it was due to not having a 'project' folder in my module. According to https://github.com/heroku/sbt-heroku/blob/master/src/main/scala/com/heroku/sbt/HerokuPlugin.scala#L29 you need a 'project' folder under the baseDirectory (that is the directory of your module, not of the whole project).
 
I tried to set herokuSkipSubProjects to false and it did not work for me but I did not investigate any further because creating the directory worked fine.

**Comment by Malax** [comment]
Closing this PR because this repository will be archived. See https://github.com/heroku/heroku-jvm-application-deployer for an alternative CLI to deploy locally compiled Scala applications.
