### ISSUE TITLE
Scala 3 Support

### ISSUE THREAD

**Issue by FunFunFine** [heroku/heroku-sbt-plugin#60]
Hey, folks

This plugin fails to work in Scala 3 projects due to the `scala-compiler` dependency being moved to `scala3-compiler`.

One can reproduce it by creating an empty project with any Scala 3 version and adding this plugin:

```shell
> g8 scala/scala3.g8
> touch example/project/plugins.sbt
> echo 'addSbtPlugin("com.heroku" % "sbt-heroku" % "2.1.4")' >> example/project/plugins.sbt
> sbt update
#...
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading org.scala-lang:scala-compiler:3.1.2
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/3.1.2/scala-compiler-3.1.2.pom
```

Indeed, this artefact [does not exist for that scala version](https://mvnrepository.com/artifact/org.scala-lang/scala-compiler) because it was moved:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/31823086/170865013-78e1258e-1f75-4847-8376-cb4c2ec19aeb.png">

**Comment by mmatloka** [comment]
I have the same issue.

**Comment by ndeverge** [comment]
Same issue here too.

**Comment by Malax** [comment]
Closing this PR because this repository will be archived. See https://github.com/heroku/heroku-jvm-application-deployer for an alternative CLI to deploy locally compiled Scala applications.
